name: redirect-tests

on: [pull_request]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./redirect/requirements.txt
          pip install -r ./rules/requirements.txt
        
      - name: Run tests for redirect
        run: |
          coverage run --branch -m pytest redirect/tests/
          coverage xml -o redirect-coverage.xml
          coverage html -d htmlcov/redirect
          coverage report

      - name: Run tests for rules
        run: |
          coverage run --branch --append -m pytest rules/tests/
          coverage xml -o rules-coverage.xml
          coverage html -d htmlcov/rules
          coverage report

      - name: Combine coverage 
        run: |
          coverage combine
          coverage xml -o combined-coverage.xml
          coverage html -d htmlcov/combined
          coverage report

      - name: Upload coverage to Pytest Coverage Commentator
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: combined-coverage.xml
